version: "3.1"
services:
  db:
    image: mysql
    container_name: db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test_db
    ports:
      - "3308:3306"
  phpmyadmin:
    image: arm64v8/phpmyadmin:latest
    restart: always
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - "8080:80"
  #php-apache-environment:
   # container_name: php-apache
    #environment:
     # - max_upload=100M
    #build:
     # context: ./php
      #dockerfile: dockerfile
    #volumes:
     # - ./php/src:/var/www/html/  #Path to folder in windows : Path to folder in Linux
    #ports:
     # - 8000:80